language: node_js

node_js:
  - '4'

cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_43f1702cd897_key -iv $encrypted_43f1702cd897_iv -in .travis/id_rsa_github.enc -out ~/.ssh/id_rsa -d

  - chmod 600 ~/.ssh/id_rsa

  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa

  - cp .travis/ssh_config ~/.ssh/config

  - git config --global user.name "Soar Lin"
  - git config --global user.email soar.lin@gmail.com

  - npm install -g hexo-cli

install:
  - npm install

before_script:
  - mv Anisina themes/
#  - git clone https://github.com/SoarLin/soarlin.github.io.git public

script:
  - hexo generate
  - ls -la themes/Anisina

#  - curl -i -X POST "https://soar.stco.tw/update" -F 'file=@db.json' -F 'index=blog' -F 'type=articles'
 - hexo deploy

#branches:
#  only:
#    - master