language: node_js

node_js:
  - 12

cache:
  directories:
      - node_modules # 不經常變動的資料夾

addons:
  ssh_known_hosts: github.com

branches:
 only:
  - master

before_install:
  - npm install -g hexo-cli
  - git clone https://github.com/next-theme/hexo-theme-next themes/next

install:
  - npm install

before_script:

script:
  - hexo clean
  - hexo generate
  # - hexo g -d  # use local 'npm run deploy' to deploy blog content

after_success:
  # - sed -i'' "/^ *repo/s~github\.com~${GITHUBHEXO_TOKEN}@github.com~" _config.yml
  # - hexo deploy
  - cd ./public
  - git init
  - git config user.name "Soar Lin"
  - git config user.email "soar.lin@gmail.com"
  - git add .
  - git commit -m "Deploy to Github Pages from hexo-github-blog"
  - git push --force --quiet "https://${GITHUBHEXO_TOKEN}@${GH_PAGE_REPO}" master:master

env:
 global:
   - GH_PAGE_REPO: github.com/soarlin/soarlin.github.io